project:
  type: website
  
execute:
  freeze: auto

website:
  title: "Git-tutorial"
  favicon: "images/rfun_logo.png"
  repo-url: https://github.com/data-and-visualization/git-tutorial/
  repo-actions: [edit, issue]
  page-footer: 
    background: light
    left: "<a href='https://rfun.library.duke.edu'>Rfun</a>"
    center: "<a href='https://library.duke.edu/data'>Center for Data & Visualization Sciences</a>"
    right: "<a href='https://library.duke.edu/'>Duke University Libraries</a>"  
  navbar:
    logo: "images/rfun_logo.png"
    background: "primary"
    left:
      - href: index.qmd
        text: Home   
      - href: ssh_keys.qmd
        text: "GitLab@Duke"
      - href: resources.qmd
        text: Resources
    right:
      - icon: github
        aria-label: GitHub
        menu:
          - text: Source Code
            url: https://github.com/data-and-visualization/git-tutorial/
          - text: Report Bug/Error
            url: https://github.com/data-and-visualization/git-tutorial/issues/new
      - icon: house-door-fill
        aria-label: Home
        menu:
          - text: "Rfun: An R learning resource"
            url: https://rfun.library.duke.edu
          - text: Center for Data & Visualization Sciences
            url: https://library.duke.edu/data/

format:
  html:
    df-print: paged
    theme: sandstone
    css: styles.css
    toc: true
    
editor: visual



