# COMMENT: redirect rules with all the fields expanded
# According to netlify domain management
# https://app.netlify.com/sites/git-github/settings/domain#custom-domains
# # Redirect default Netlify subdomain to primary domain
# https://git-github.netlify.com/* https://git-rfun.library.duke.edu/:splat 301!
[[redirects]]
  from = "https://git-github.netlify.com/*"
  to = "https://git-rfun.library.duke.edu/:splat"
  status = 301
  force = true
