---
title: Resources
site: distill::distill_website
---

## Slides

- [Research Reproducibility, 2021](https://docs.google.com/presentation/d/1FJlC01xATiOfPmUxURHtMI6IUY1Sr7aMIQ0J4F2YJHU/edit?usp=sharing)

## Social Coding Sites

- https://github.com
- https://gitlab.com
- https://bitbucket.org 

- Duke’s [GitLab](https://gitlab.oit.duke.edu/) Instance

    - [Managing SSH keys](https://gitlab.oit.duke.edu/help/ssh/README)
    
## GUI Git Clients

- [RStudio](https://rstudio.com) -- Free. Great for useRs
- [Sublime's Merge](https://www.sublimemerge.com/) --   Downloaded and evaluated for free. $100 / 3-years of upgrades.  
- GitKracken -- **Free** if you have the [GitHub Student](https://education.github.com/pack) Pack or the [GitHub Teacher toolbox](https://www.gitkraken.com/github-teacher-toolbox)
- [SourceTree](https://www.sourcetreeapp.com/) --  Free. (defaults to use with [BitBucket](https://bitbucket.org/))
    

### Packages

- https://usethis.r-lib.org/
- [`holepunch`](https://karthik.github.io/holepunch/)  to make your reproducible code a container on binder.org

### Free Book

- [Happy Git and GitHub for the useR](http://happygitwithr.com/)

### Handy Article
- [10 Common Problems / Solutions](https://www.codementor.io/citizen428/git-tutorial-10-common-git-problems-and-how-to-fix-them-aajv0katd)

## Reproducibility

- [Writing clear code: Tools for Reproducible Research](http://kbroman.org/Tools4RR/assets/lectures/07_clearcode.pdf)
- [Initial Steps Toward Reproducible Research](http://kbroman.org/steps2rr/) 
- Making your research reproducible with TIER + R + GitHub [Slides]. Cetinkaya-Rundel, M. (2016). Open Science Framework. Retrieved from https://osf.io/phyau